### PR TITLE
WIP, RFC: Try wheels

### PR DESCRIPTION
**Pull request by jakirkham**
Pending the outcome of the discussion in issue ( https://github.com/conda-forge/conda-smithy/issues/608 ).

Attempts to build a wheel of python-snappy for those wishing to pip install it instead of conda install it. This relies on a not totally finalized version of `conda-smithy` to get `conda-build` 3, which simplified this exercise. The wheels built will not be one-to-one with typical wheels in all cases. For example, we build on CentOS 6 instead of CentOS 5 used by manylinux1. Also we build with the macOS 10.9 SDK instead of 10.6. Though the wheels I built locally seem to match this. As for Windows this should be a close match to what is expected.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by jakirkham** [comment]
This doesn't quite work correctly as `snappy` is not included in the wheel for some reason. Raised as issue ( https://github.com/conda/conda-build/issues/2736 ).

**Comment by djsutherland** [comment]
Is it expected that the wheel _would_ include the shared library dependency? The docs seem scarce and I haven't looked at the source, but
```
  - type: wheel
    requirements:
      build:
        - python
        - snappy 1.1.6|1.1.7
```
seems like maybe it needs a `requirements/run` or...something else to specify that it should include `snappy`.

(This is cool if it'll work, though!)

**Comment by jakirkham** [comment]
Think it ignores run requirements for wheels. At least that was my experience working on a similar problem earlier. Though happy to give it another try.

Not sure if it should be expected. From what I’ve seen people run `auditwheel repair` to inject shared libraries into the wheel. That said, don’t know if that is the preferred strategy or just another way to accomplish it.

Suppose one could statically link libraries to solve the issue. Though wouldn’t like that to spread generally in conda-forge if it could be avoided.

Haven’t even been playing with this 24hrs yet. So am sure there’s more to learn. :)

**Comment by jakirkham** [comment]
Might also be able to copy snappy somewhere in the source directory. Not sure though.

**Comment by jakirkham** [comment]
The failure in [this Windows 32-bit Python 2.7 log]( https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/1.0.24/job/mronmj2erer6ts6d ) is a little bizarre. Not totally sure what happened there. Maybe adding the compiler for the wheel step would help?

Edit: Seems to be happening in all of the Windows 32-bit builds. Here's the logs for [Windows 32-bit Python 3.5]( https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/1.0.24/job/o4k6ctrf9ah4948c ) and [Windows 32-bit Python 3.6]( https://ci.appveyor.com/project/conda-forge/python-snappy-feedstock/build/1.0.24/job/x6jayncc8r4tog5r ).

cc @msarahan

**Comment by martindurant** [comment]
Outdated: python-snappy will just call cramjam from now on, so be supported on any platform it is.

**Pull request closed without merging**
